---
title: "writing_functions"
author: "Kristi Chau"
date: "10/24/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rvest)

set.seed(1)
```


## Get started

We're going to write some functions.

Here's z-scores
```{r}
x = rnorm(n = 30, mean = 4, sd = 2.3)
x_again = rnorm(n = 30, mean = 6, sd = .3)

(x - mean(x)) / sd(x)
(x_again - mean(x_again)) / sd(x_again)
```

Now a function
```{r}
z_score = function(x_arg) {
  
  if (!is.numeric(x_arg)) { 
    stop("x should be numeric")
  } else if (length(x_arg) < 3) { 
    stop("x should be longer than 3")
  }
  
  (x_arg - mean(x_arg)) / sd(x_arg)
  
}
```

Try out the function
```{r}
z_score(x_arg = x_again) ## need to tell the function what x is equal to

## z_score(x_arg = 3)
## z_score(x_arg = "my name is jeff")
## z_score(x_arg = c(TRUE, TRUE, FALSE, TRUE))
## z_score(x_arg = iris)
```


## Multiple outputs

```{r}
mean_and_sd = function(input_x) {
  
    if (!is.numeric(input_x)) { 
    stop("x should be numeric")
  } else if (length(input_x) < 3) { 
    stop("x should be longer than 3")
  }
  
  list(
    mean_input = mean(input_x),
    sd_input = sd(input_x),
    z_score = (input_x - mean(input_x)) / sd(input_x)
  )
  
}
```

Test this function
```{r}
mean_and_sd(input_x = x)
```


## Multiple inputs

```{r}
sim_data = tibble(
  x = rnorm(30, mean = 1, sd = 1),
  y = 2 + 3 * x + rnorm(30, 0, 1)
)

ls_fit = lm(y ~ x, data = sim_data) ## fits simple linear regreession
  
beta0_hat = coef(ls_fit)[1] ## extract estimated intercept
beta1_hat = coef(ls_fit)[2] ## estimated slope
```

```{r}
sim_regression = function(n, beta0, beta1) {
  
  sim_data = tibble(
    x = rnorm(n, mean = 1, sd = 1),
    y = beta0 + beta1 * x + rnorm(n, 0, 1)
    )

  ls_fit = lm(y ~ x, data = sim_data)
  
  tibble(
    beta0_hat = coef(ls_fit)[1],
    beta1_hat = coef(ls_fit)[2]
  )
  
}

sim_regression(n = 3000, beta0 = 17, beta1 = -3)
```





